# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = atmel-dfu

#VIA & VIAL Support
VIA_ENABLE = yes
VIAL_ENABLE = yes

# Build Options
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
UNICODE_ENABLE = no
MIDI_ENABLE = no
CUSTOM_MATRIX = lite
NO_USB_STARTUP_CHECK = yes
LTO_ENABLE = yes

SRC += matrix.c
QUANTUM_LIB_SRC += i2c_master.c

VIAL_ENCODERS_ENABLE = no
ENCODERS_ENABLE = no
ENCODER_MAP_ENABLE = no
SWAP_HANDS_ENABLE= no

MUSIC_ENABLE = no
QMK_SETTINGS = yes
